//= require "extensions/number"
//= require "extensions/element"
//= require "extensions/element/insert"
//= require "extensions/event"
//= require "extensions/events/mouse_wheel"
//= require "extensions/effects"